spring.application.name=exercise

spring.jpa.hibernate.ddl-auto=update

# ?? JWT ??? (dev?? ??? ??)
jwt.secret=flap-secret-key-flap-secret-key-flap-secret-key
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=1209600000
