spring.application.name=exercise

spring.datasource.url=jdbc:postgresql://localhost:5432/futsal_reservation
spring.datasource.username=postgres
spring.datasource.password=0417

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true